config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  root :to => 'posts#index'
  get "/about" => "homes#about"
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :customers, only: [:show, :edit, :update] do
  	resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/search' => 'search#search', as: 'search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post
  validates :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :customer
  validates :name, presence: true
  validates :user_name, presence: true
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }
  
  def follow(other_customer)
    unless self == other_customer
      self.relationships.find_or_create_by(follow_id: other_customer.id)
    end
  end

  def unfollow(other_customer)
    relationship = self.relationships.find_by(follow_id: other_customer.id)
    relationship.destroy if relationship
  end

  def following?(other_customer)
    self.followings.include?(other_customer)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  attachment :image
  acts_as_taggable
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :sentence, presence: true

  def liked_by?(customer)
    likes.where(customer_id: customer.id).exists?
  end

  belongs_to :area
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :customer
  belongs_to :follow, class_name: 'Customer'

  validates :customer_id, presence: true
  validates :follow_id, presence: true
end

app/models/tag.rb
#class Tag < ApplicationRecord
#  belongs_to :post
#end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :init_search

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_name, :phone_number ])
  end
  
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def init_search
    @search = Post.ransack(params[:q])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = current_customer.comments.new(comment_params)
    @comment.post_id = @post.id
    if @comment.save
      redirect_to post_path(params[:post_id])
    else
      render 'posts/show'
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end
  
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  before_action :ensure_correct_customer, only: [:edit, :update, :destroy]
  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_path
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :user_name, :profile_image, :introduction)
  end
  def ensure_correct_customer
    @customer = Customer.find(params[:id])
    redirect_to(root_path) unless current_customer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    like = current_customer.likes.new(post_id: post.id)
    like.save
    redirect_to root_path
  end

  def destroy
    post = Post.find(params[:post_id])
    like = current_customer.likes.find_by(post_id: post.id)
    like.destroy
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_customer!, only: [:edit, :update, :destroy]
before_action :ensure_correct_customer, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
    @areas = Area.all
  end

  def index
    @posts = Post.all
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}")
    elsif params[:area_id]
      @area = Area.find(params[:area_id])
      @posts = Post.where(area_id: params[:area_id])
    elsif params[:q]
      @word = params["q"]["sentence_cont"]
      @posts = @search.result
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @customer = Customer.find(@post.customer_id)
  end

  def create
    @post = Post.new(post_params)
    @post.customer_id = current_customer.id
    if @post.save
      tags = Vision.get_image_data(@post.image)    
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      redirect_to root_path
    else
      @areas = Area.all
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @areas = Area.all
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end


  private
  def post_params
    params.require(:post).permit(:image, :sentence, :area_id, :tag_list)
  end
  
  def ensure_correct_customer
    @post = Post.find(params[:id])
    unless @post.customer == current_customer
    redirect_to root_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_customer

  def create
    following = current_customer.follow(@customer)
    if following
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to @customer
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to @customer
    end
  end

  def destroy
    following = current_customer.unfollow(@customer)
    if following
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to @customer
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to @customer
    end
  end

  private
  def set_customer
    @customer = Customer.find(params[:customer_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/customers/edit.html.erb
  <%= form_with model:@customer, local:true do |f| %>

  <%#プロフィール写真の変更 %>
        <div class="form-group has-icon">
          <div class="customer-edit-image">
            <%= attachment_image_tag @customer, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
          </div>
          <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        </div>

        <div class="field col-xs-12">
          <%= f.label :"名前", class:"col-xs-2" %>
          <%= f.text_field :name, autofocus: true, class:"col-xs-2" %><br>
        </div>

        <div class="field col-xs-12">
          <%= f.label :"ユーザーネーム", class:"col-xs-2" %>
          <%= f.text_field :user_name, autofocus: true , class:"col-xs-2" %>
        </div>

        <div class="field col-xs-12">
          <%= f.label :"自己紹介" , class:"col-xs-2"%>
          <%= f.text_area :introduction, autofocus: true, class:"form-caption", rows:"5" %>
        </div>

        <div class="field col-xs-12">
          <%= f.label :"メール", class:"col-xs-2" %>
          <%= f.text_field :email, autofocus: true %>
        </div>

        <div class="field col-xs-12">
          <%= f.label :"電話番号(ハイフン無し)" , class:"col-xs-2"%>
          <%= f.text_field :phone_number, autofocus: true %>
        </div>
        
        <div class="col-xs-12">
          <%= f.submit "編集する" %>
        </div>
  <% end %>

app/views/customers/show.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" />
 <div class="row">
    <div class="col-md-12">
        <h3><%= @customer.name %>&nbsp;&nbsp;詳細</h3>
        <div class = "profile">
          <div class="col-sm-2">
            <div class = "username">
              <%= attachment_image_tag @customer, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle profile-img", fallback: "no_image.jpg" %>
              <p><%= @customer.user_name %></p>
            </div>
          </div>
          <div class="col-sm-10">
            <% if current_customer != nil %> 
              <% if @customer.id == current_customer.id %>
                <div class = "profile-info">
                  <p><%= link_to "プロフィール編集", edit_customer_path(@customer) %></br/>
              <% end %>
            <% end %>
            <p><%= render 'relationships/follow_button', customer: @customer %></p>
                フォロー数: <%= @customer.followings.count %>&nbsp;&nbsp;&nbsp;&nbsp;
                フォロワー数: <%= @customer.followers.count %></br>
            <p><%= @customer.introduction %></p>
              </div>
           </div>
        </div>
      <% @posts.each do |post| %>
          <div class="masonry-block">
            <%= link_to post_path(post.id) do %>
              <%= attachment_image_tag post, :image, :size =>'300x200' %>
            <% end %>
            <p><%= post.sentence %></p>
              <div class="block-reaction">
                    <% if post.liked_by?(current_customer) %>
                      <%= link_to post_likes_path(post), method: :delete do %>
                        <i class="fa fa-heart",aria-hidden="true", style="color: red;"></i>
                        <%= post.likes.count %>
                      <% end %>
                    <% else %>
                      <%= link_to post_likes_path(post), method: :post do %>
                        <i class="fa fa-heart" aria-hidden="true"></i>
                        <%= post.likes.count %>
                      <% end %>
                    <% end %>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                      <i class="fa fa-comment">
                        <%= link_to "#{post.comments.count}", root_path %>
                      </i>
              </div>
          </div>
      <% end %>   
    </div>
  </div>

app/views/posts/edit.html.erb
<div class="row">
    <div class="Title">
      <h2>編集する</h2>
    </div>
    <br>
    
    <%= form_with model:@post, local:true do |f| %>
      <%= attachment_image_tag @post, :image, :size =>'300x200' %>
      </br>
      <%= f.text_area :sentence, autofocus: true, class:"form-caption", rows:"5", placeholder:"投稿文" %>
      </br>
      <%= f.label :area_id, 'エリア' %>
      </br>
      <%= f.collection_select(:area_id, @areas, :id, :continent, include_blank: true, autofocus: true) %>
      </br>
      <%= f.label :tag_list, 'タグ' %>
      <%= f.text_field :tag_list, :value =>@post.tag_list.join(','), autofocus: true, class: "form-control" %>
      </br>
      <%= f.submit "編集する" %>
    <% end %>
    
</div>

app/views/posts/index.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" />
  <div class="row">
     <div class="col-md-1">
      <h4>エリア</h4>
        <div class="area">
          <% Area.all.each do |area| %>
              <%= link_to area.continent, posts_path(area_id: area.id) %>
          <% end %>
        </div>
    </div>
    <% if @area %>
      <p><%= @area.continent %></p>
    <% end %>
    <% if @word %>
      <p><%= @word %></p>
    <% end %>
    <div class="col-md-11">
      <% @posts.each do |post| %>
            <div class="masonry-block">
                    <%= link_to post_path(post.id) do %>
                      <%= attachment_image_tag post, :image, :size =>'300x200' %>
                    <% end %>
                <div class="block-content">
                  <%= attachment_image_tag post.customer, :profile_image, :fill, 50, 50, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
                  <h3 class="block-title">
                    <%= link_to customer_path(post.customer_id) do %>
                      <%= post.customer.name %>
                    <% end %>
                  </h3>
                  <p><%= post.sentence %></p>
                  <div class="block-reaction">
                  <% if customer_signed_in? %>
                    <% if post.liked_by?(current_customer) %>
                        <%= link_to post_likes_path(post), method: :delete do %>
                          <i class="fa fa-heart",aria-hidden="true", style="color: red;"></i>
                          <%= post.likes.count %>
                        <% end %>
                    <% else %>
                        <%= link_to post_likes_path(post), method: :post do %>
                          <i class="fa fa-heart" aria-hidden="true"></i>
                          <%= post.likes.count %>
                        <% end %>
                    <% end %>
                  <% else %>
                    <i class="fa fa-heart" aria-hidden="true"></i>
                    <%= post.likes.count %>
                  <% end %>
                      <i class="fa fa-comment">
                      <%= link_to "#{post.comments.count}", post_path(post.id) %>
                      </i>
                  
                  </div>
                  <% post.tag_counts_on(:tags).each do |tag| %>
                    <%= link_to tag.name, posts_path(tag_name:tag.name), class: "label label-primary" %>
                  <% end %>
                </div>
            </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="text-left">
    <div class="Title">
      <h2>新規投稿</h2>
    </div>
    <br>
    <% if @post.errors.any? %>
          <div class = "alert">
            <ul>
              <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
    <br>
    <div class="new-post">
      <%= form_with model:@post, local:true do |f| %>
      
        <%= f.attachment_field :image %>
        </br>
        <%= f.text_area :sentence, class:"form-caption", rows:"5", placeholder:"投稿文" %>
        </br>
        <%= f.label :area_id, 'エリア' %>
        </br>
        <%= f.collection_select(:area_id, @areas, :id, :continent, include_blank: true) %>
        </br>
        <%= f.label :tag_list, 'タグ' %>
        <%= f.text_field :tag_list, class: "form-control", :value =>@post.tag_list.join(',') %>
        </br>
        <%= f.submit "投稿する" %>
      <% end %>
    </div>
  </div>

</div>

app/views/posts/show.html.erb
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" />

  <div class="row">
      <div class="col-3">
        <%= attachment_image_tag(@post, :image, :size =>'390x260', fallback: "no_image.jpg") %>
      </div>
  </div>
  <div class="row">
      <div class="col-9">
        <div class="user">
          <p><%= attachment_image_tag @post.customer, :profile_image, :fill, 50, 50, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
          </p>
          <%= link_to customer_path(@post.customer_id) do %>
              <h4><%= @post.customer.user_name %></h4>
          <% end %>
          
          <p><%= render 'relationships/follow_button', customer: @post.customer %></p>
        </div>
        <%= @post.sentence %>
          <% if current_customer != nil %> 
            <%#自分の投稿の詳細画面の場合に編集ページへのリンクを表示する %>
            <% if @post.customer_id == current_customer.id %>
                <p><%= link_to "編集", edit_post_path(@post), class: "glyphicon glyphicon-edit" %></p></br>
                <p><%= link_to "削除", post_path(), method: :delete, class: "btn btn-danger pull-right" %></p></br>
            <% end %>
          <% end %>
            <div class="block-reaction">
                  <% if customer_signed_in? %>
                    <% if @post.liked_by?(current_customer) %>
                        <%= link_to post_likes_path(@post), method: :delete do %>
                          <i class="fa fa-heart",aria-hidden="true", style="color: red;"></i>
                          <%= @post.likes.count %>
                        <% end %>
                    <% else %>
                        <%= link_to post_likes_path(@post), method: :post do %>
                          <i class="fa fa-heart" aria-hidden="true"></i>
                          <%= @post.likes.count %>
                        <% end %>
                    <% end %>
                  <% else %>
                    <i class="fa fa-heart" aria-hidden="true"></i>
                    <%= @post.likes.count %>
                  <% end %>
                      <i class="fa fa-comment">
                      <%= @post.comments.count %>
                      </i>
                  <div>
                    <% @post.tag_counts_on(:tags).each do |tag| %>
                      <%= link_to tag.name, posts_path(tag_name:tag.name), class: "label label-primary" %>
                    <% end %>
                  </div>
            </div>
            <div class="block-comment">
              <% if current_customer != nil %> 
                <% if @comment.errors.any? %>
                  <div class = "alert">
                    <ul>
                      <% @comment.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
                <%= form_with(model:[@post, @comment], local: true) do |f| %>
                      <%= f.text_area :comment, rows:'2', class: "form-control",placeholder: "コメントを追加" %></br>
                  <%= f.submit "追加する", class: "btn btn-lg btn-base-1 mt-20" %>
                <% end %>
              <% end %>
              　<% @post.comments.each do |comment| %>
                  <div class="comment">
                    <div class="comment-body bb">
                      <div class="comment-avatar">
                        <div class="avatar">
                          <%= image_tag('no_image.jpg', style: "width: 60px; height: 60px;") %>
                        </div>
                      </div>
                      <div class="comment-text">
                        <div class="comment-author clearfix">
                          <a href="#" class="link-author"><%= link_to comment.customer.user_name, customer_path(comment.customer_id) %></a>
                          <span class="comment-meta">
                            <span class="comment-date"><%= comment.created_at.strftime('%Y/%m/%d') %></span>
                          </span>
                        </div>
                        <div class="comment-entry"><%= comment.comment %></div>
                        <% if current_customer != nil %> 
                           <% if comment.customer.id == current_customer.id %>
                            <div>
                              <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete, class: "btn btn-danger pull-right" %>
                            </div>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
            </div>
        </div>
  </div>

app/views/relationships/_follow_button.html.erb
<% if current_customer != nil %>  
  <% if current_customer != customer %>
      <% if current_customer.following?(customer) %>
        <%= link_to "フォローを外す", customer_relationships_path(customer.id), method: :delete, class: 'btn btn-danger'  %>
      <% else %>
        <%= link_to "フォローする", customer_relationships_path(customer.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
  <% end %>
<% end %>