config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  root :to => 'posts#index'
  get "/about" => "homes#about"
  
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
  end
  resources :customers, only: [:show, :edit, :update] do
  	resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  get '/search' => 'search#search', as: 'search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :post
  validates :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :customer
  validates :name, presence: true
  validates :user_name, presence: true
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }
  
  def follow(other_customer)
    unless self == other_customer
      self.relationships.find_or_create_by(follow_id: other_customer.id)
    end
  end

  def unfollow(other_customer)
    relationship = self.relationships.find_by(follow_id: other_customer.id)
    relationship.destroy if relationship
  end

  def following?(other_customer)
    self.followings.include?(other_customer)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :customer
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  attachment :image
  acts_as_taggable
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :sentence, presence: true

  def liked_by?(customer)
    likes.where(customer_id: customer.id).exists?
  end

  belongs_to :area
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :customer
  belongs_to :follow, class_name: 'Customer'

  validates :customer_id, presence: true
  validates :follow_id, presence: true
end

app/models/tag.rb
#class Tag < ApplicationRecord
#  belongs_to :post
#end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = current_customer.comments.new(comment_params)
    @comment.post_id = @post.id
    if @comment.save
      redirect_to post_path(params[:post_id])
    else
      render 'posts/show'
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end
  
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    like = current_customer.likes.new(post_id: post.id)
    like.save
    redirect_to root_path
  end

  def destroy
    post = Post.find(params[:post_id])
    like = current_customer.likes.find_by(post_id: post.id)
    like.destroy
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_customer!, only: [:edit, :update, :destroy]
before_action :ensure_correct_customer, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
    @areas = Area.all
  end

  def index
    @posts = Post.all
    if params[:tag_name]
      @posts = Post.tagged_with("#{params[:tag_name]}")
    elsif params[:area_id]
      @area = Area.find(params[:area_id])
      @posts = Post.where(area_id: params[:area_id])
    elsif params[:q]
      @word = params["q"]["sentence_cont"]
      @posts = @search.result
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @customer = Customer.find(@post.customer_id)
  end

  def create
    @post = Post.new(post_params)
    @post.customer_id = current_customer.id
    if @post.save
      tags = Vision.get_image_data(@post.image)    
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      redirect_to root_path
    else
      @areas = Area.all
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    @areas = Area.all
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end


  private
  def post_params
    params.require(:post).permit(:image, :sentence, :area_id, :tag_list)
  end
  
  def ensure_correct_customer
    @post = Post.find(params[:id])
    unless @post.customer == current_customer
    redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_header.html.erb
<div class="page-header">
  <div class="container">
      <span class="logo-image"><%= link_to image_tag(asset_path("logo1.png"), style: "width: 400px; height: 85px;"), root_path %> </span>
      <div class="search-form">
          <%= form_with model: @search, url: root_path, method: :get, local: true do |f| %>
            <%= f.search_field :sentence_cont %>
            <%= f.submit '検索' %>
          <% end %>
      </div>
       
       <ul class="nav navbar-nav navbar-right">

        <% if customer_signed_in? %>
        <!--顧客がログインしている場合-->
          <li><%= link_to '', root_path, class: "glyphicon glyphicon-home icon", style: "font-size: 25px" %></li>
          <li><%= link_to '', about_path, class: "glyphicon glyphicon-info-sign icon", style: "font-size: 25px" %></li>
          <li><%= link_to '', new_post_path, class: "glyphicon glyphicon-plus-sign icon", style: "font-size: 25px" %></li>
          <li><%= link_to '', customer_path(current_customer), class: "glyphicon glyphicon-user icon", style: "font-size: 25px" %></li>
          <li><%= link_to '', destroy_customer_session_path, method: :delete, class: "glyphicon glyphicon-log-out icon", style: "font-size: 25px" %></li>
        <% else %>
        <!--ログインしていない場合-->
          <li><%= link_to '', root_path, class: "glyphicon glyphicon-home icon", style: "font-size: 25px" %></li>
          <li><%= link_to '', about_path, class: "glyphicon glyphicon-info-sign icon", style: "font-size: 25px" %></li>
          <li><%= link_to '', new_customer_registration_path, class: "glyphicon glyphicon-file icon", style: "font-size: 25px" %></li>
          <li><%= link_to '', new_customer_session_path, class: "glyphicon glyphicon-log-in icon", style: "font-size: 25px" %></li>

        <% end %>
      </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TabiPic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
     <div class='body'>
      <div class='container'>
        <%= yield %>
      </div>
     </div>
  </body>
</html>